from flask import Flask, request, jsonify
import joblib
import pandas as pd
import time

app = Flask(__name__)

print("Loading model and explainer...")
# Load artifacts generated by train_model.py
try:
    model = joblib.load('model.joblib')
    explainer = joblib.load('explainer.joblib')
    expected_features = joblib.load('feature_names.joblib')
    print("Successfully loaded model and explainer.")
except Exception as e:
    print(f"Error loading model artifacts: {e}")
    print("Make sure to run 'python train_model.py' first!")

@app.route('/', methods=['GET'])
def index():
    return "API is running! Use POST /predict to get predictions."

@app.route('/predict', methods=['POST'])
def predict():
    start_time = time.time()
    try:
        data = request.get_json()
        if not data or 'sensor_readings' not in data:
            return jsonify({'error': 'Missing sensor_readings in request body.'}), 400
        
        sensor_readings = data['sensor_readings']
        
        # Convert input dict to DataFrame with expected feature order
        df = pd.DataFrame([sensor_readings], columns=expected_features)
        
        # Calculate Failure Probability (assuming class 1 is failure)
        probability_distribution = model.predict_proba(df)[0]
        failure_probability = float(probability_distribution[1])
        
        # Generate SHAP-based explanation
        shap_values = explainer.shap_values(df)
        
        # Handling SHAP output shape differences between versions for classifiers
        if isinstance(shap_values, list): # Older SHAP versions
            sv = shap_values[1][0].tolist() 
        elif len(shap_values.shape) == 3: # Some newer SHAP versions
            sv = shap_values[0, :, 1].tolist()
        else: 
            sv = shap_values[0].tolist()

        # Create a feature-to-shap-value dictionary
        shap_explanation = dict(zip(expected_features, sv))
        
        # API Latency Check (Target < 50ms)
        latency_ms = (time.time() - start_time) * 1000
        
        # Construct output
        response = {
            "failure_probability": failure_probability,
            "shap_explanation": shap_explanation,
            "latency_ms": latency_ms,
            "latency_status": "PASS" if latency_ms < 50 else "FAIL"
        }
        
        return jsonify(response)

    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    # Run the application
    app.run(host='0.0.0.0', port=5000)
